services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Roda a imagem de desenvolvimento
      target: development
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT}:3000
    depends_on:
      - database-${DATABASE}

  database-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USERNAME=${DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - database_mysql_data:/var/lib/mysql

  database-postgres:
    image: postgres:14.5
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - database_postgres_data:/var/lib/postgresql/data   

  adminer:
    image: adminer:4.8.1
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - database-${DATABASE}

volumes:
  node_modules: {}
  database_mysql_data: {}  
  database_postgres_data: {}
