services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Roda a imagem de desenvolvimento
      target: development
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT}:3000
    depends_on:
      - database

  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USERNAME=${DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data: {}
  node_modules: {}
